### ISSUE TITLE
多个模型在modelscope不存在

### ISSUE THREAD

**Issue by yaleimeng** [X-D-Lab/Sunsimiao#14]
如图所示：
![image](https://github.com/user-attachments/assets/7e221c98-e135-44ee-87d8-39f117734d39)

**Comment by yaleimeng** [comment]
但是存在 https://www.modelscope.cn/models/X-D-Lab/Sunsimiao-Qwen-7B   更新日期是2023年11月30日。。里面权重也是8个月前的。
![image](https://github.com/user-attachments/assets/a36b9386-2e28-42ea-9469-4fdca1543ec4)
然而页面主页写的是  [Jul 23,2024][new!]🚀🚀🚀   Sunsimiao-7B发布！
这是怎么回事？

**Comment by h563k** [comment]
同问这个问题

**Comment by jingnant** [comment]
> 如图所示： ![image](https://private-user-images.githubusercontent.com/28124722/355037030-7e221c98-e135-44ee-87d8-39f117734d39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNjU5MDQsIm5iZiI6MTcyNTI2NTYwNCwicGF0aCI6Ii8yODEyNDcyMi8zNTUwMzcwMzAtN2UyMjFjOTgtZTEzNS00NGVlLTg3ZDgtMzlmMTE3NzM0ZDM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDA4MjY0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwNWY0YTk3MTUwOTk3NGFlMjI0M2IzYTRkZjA3ODkzZDEyNjNiNWZmNzNiNjFlODdmNjEzZTJmNzA5NDVkMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z7WwHLmofBM7MrX2b-3vhg1RCFsmMsZfvTre43jnB_g)

您好，Sunsimiao-7B的modelscope链接已公开，请查看

**Comment by jingnant** [comment]
Sunsimiao-7B的modelscope权重已更新，请查看

**Comment by yaleimeng** [comment]
@jingnant  谢谢您的回应。
