### ISSUE TITLE
想问一下作者是不是经过了增量预训练，还是仅仅靠监督微调

### ISSUE THREAD

**Issue by lordlxh** [X-D-Lab/Sunsimiao#3]
大概需要的数据量是多少条呢

**Comment by thomas-yanxin** [comment]
目前您看到的这几个有些旧的模型是仅仅经过了SFT，数据量在十万这个**量级**。最近我们会有一些开源更新。

**Comment by lordlxh** [comment]
好的，非常感谢，可以问一下大佬十万条数据跑了多少个epoch吗

**Comment by thomas-yanxin** [comment]
解释一下哈，这个是十万的数据量级（在这个范围里，不同的时期可能会有不同的数据加入进去，所以没法特别具体的说是多少），不是十万哈~跑了1个epoch。后面我们可能会出一个比较完整实验的tech report。
